In [19]:
# importing numpy as np
import numpy as np

# a function that squares all the values
# in a sequence
def squares(values):
    result = []
    for v in values:
        result.append(v * v)
    return result
to_square = range(100000)
%timeit squares(to_square)




19.7 ms ± 104 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [20]:
# now lets do this with a numpy array
array_to_square = np.arange(100000)
%timeit array_to_square ** 2


80 µs ± 941 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
[0 1 2 3 4 5 6 7 8 9]


In [21]:
# a simple array
a1 = np.array([1, 2, 3, 4, 5])
a1

array([1, 2, 3, 4, 5])

In [22]:
type(a1)

numpy.ndarray

In [25]:
# how many elements?
np.size(a1)

# another way
a1.size

5

In [33]:
# any float in the sequences makes
# it an array of floats
a2 = np.array([1, 2, 3, 4.0, 5.0])
a2

array([ 1.,  2.,  3.,  4.,  5.])

In [34]:
# array is all of one type (float64 in this case)
a2.dtype

dtype('float64')

In [35]:
# shorthand to repeat a sequence 10 times
a3 = np.array([0]*10)
a3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
# convert a python range to numpy array
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
# create a numpy array of 10 0.0's
np.zeros(10)


array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [43]:
# another way
np.array([0.]*10)

array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [44]:
# force it to be of int instead of float64
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [45]:
# make "a range" starting at 0 and with 10 values
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
# 0 <= x < 10 increment by two
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [52]:
# 10 >= x > 0, counting down
np.arange(10, 0, -1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [53]:
# evenly spaced #'s between two intervals
np.linspace(0, 10, 11)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [84]:
# multiply numpy array by 2
a1 = np.arange(0, 10)
a1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [57]:
# add two numpy arrays
a2 = np.arange(10, 20)
a1 + a2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [65]:
# create a 2-dimensional array (2x2)
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [75]:
# create a 1x20 array, and reshape to a 5x4 2d-array
m = np.arange(0, 20).reshape(5, 4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [78]:
# size of any dimensional array is the # of elements
np.size(m)

# another way
m.size

20

In [79]:
# can ask the size along a given axis (0 is rows)
np.size(m, 0)

5

In [82]:
# and 1 is the columns
np.size(m, 1)

4

In [85]:
# select 0-based elements 0 and 2
a1[0], a1[2]

(0, 2)

In [86]:
# select an element in 2d array at row 1 column 2
m[1, 2]

6

In [87]:
# all items in row 1
m[1,]

array([4, 5, 6, 7])

In [90]:
# all items in column 2
m[:,2]

array([ 2,  6, 10, 14, 18])

In [93]:
# which items are less than 2?
a = np.arange(5)
a < 2

array([ True,  True, False, False, False], dtype=bool)